packages:
  - "packages/*"

allowBuilds:
  better-sqlite3: false
  core-js: false
  esbuild: false
  sharp: false

onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp

patchedDependencies:
  cursor-history@0.18.0: patches/cursor-history@0.18.0.patch
