export const creatorsData = [
  {
    name: 'Alper Ortac',
    slug: 'alper-ortac',
    xHandle: 'alperortac',
    avatarUrl: 'https://pbs.twimg.com/profile_images/1568620530281992197/q4uX7XTK_400x400.jpg',
    verified: true,
    personalPages: [{ name: 'X', url: 'https://x.com/alperortac' }],
    projectPages: [{ name: 'GoodWatch', url: 'https://goodwatch.app' }],
    bio: 'Windsurf is my main driver. Accompanied by many sidekick tools.',
  },
  {
    name: 'Anthony',
    slug: 'anthony',
    xHandle: undefined,
    discordUserId: '105048063873126400',
    avatarUrl: 'https://levelingo.com/head.png',
    verified: true,
    personalPages: [{ name: 'Discord', url: 'https://discord.com/users/105048063873126400' }],
    projectPages: [{ name: 'Levelingo', url: 'https://levelingo.com' }],
    bio: 'Building Levelingo. Claude Max power user.',
  },
  {
    name: 'Chase Myers',
    slug: 'chase-myers',
    xHandle: 'chasem-dev',
    avatarUrl: 'https://chasem.dev/me.jpg',
    verified: true,
    personalPages: [{ name: 'GitHub', url: 'https://github.com/chasem-dev' }],
    projectPages: [{ name: 'Software Aura', url: 'https://softwareaura.com/' }],
    bio: 'Cursor Pro user with Codex extension.',
  },
  {
    name: 'Will Ness',
    slug: 'will-ness',
    xHandle: 'N3sOnline',
    avatarUrl: 'https://pbs.twimg.com/profile_images/1874518618743910400/FD_XvVH9_400x400.jpg',
    verified: true,
    personalPages: [{ name: 'X', url: 'https://x.com/N3sOnline' }],
    projectPages: [{ name: 'DoThisTask', url: 'https://www.dothistask.ai' }],
    bio: 'Claude Max + Claude Code + Wispr Flow + Perplexity stack.',
  },
  {
    name: 'Mark Perera',
    slug: 'mark-perera',
    xHandle: 'nipun056',
    avatarUrl: 'https://pbs.twimg.com/profile_images/1864347572053164032/PlDvx1Zz_400x400.jpg',
    verified: true,
    personalPages: [{ name: 'GitHub', url: 'https://github.com/nipun056' }],
    projectPages: [{ name: 'Google AI Studio', url: 'https://aistudio.google.com' }],
    bio: 'Google AI Pro user with Antigravity IDE.',
  },
  {
    name: 'Ivan Boroja',
    slug: 'ivan-boroja',
    xHandle: 'ivanboroja',
    avatarUrl: 'https://pbs.twimg.com/profile_images/2001689148944687104/xzaZoaLc_400x400.jpg',
    verified: true,
    personalPages: [{ name: 'X', url: 'https://x.com/ivanboroja' }],
    projectPages: [{ name: 'Artasaka', url: 'https://www.artasaka.com' }],
    bio: 'Full-stack creative developer with a comprehensive tool stack for design and development.',
  },
  {
    name: 'AL',
    slug: 'iambrutefyal',
    xHandle: 'iambrutefyAL',
    avatarUrl: 'https://pbs.twimg.com/profile_images/1979072577759739904/MSw2JQhb_400x400.jpg',
    verified: true,
    personalPages: [{ name: 'X', url: 'https://x.com/iambrutefyAL' }],
    projectPages: [{ name: 'Voice Ink', url: 'https://tryvoiceink.com/' }],
    bio: 'Claude Code + Google AI Studio workflow for rapid feature shipping.',
  },
  {
    name: 'Sabih Sarowar',
    slug: 'sabih-sarowar',
    xHandle: 'da_green_hermit',
    avatarUrl: 'https://pbs.twimg.com/profile_images/1915237824372105217/UzarVezl_400x400.jpg',
    verified: true,
    personalPages: [{ name: 'X', url: 'https://x.com/da_green_hermit' }],
    projectPages: [],
    bio: 'Windsurf early adopter + Superwhisper for voice-to-text.',
  },
  {
    name: 'Schuyler',
    slug: 'schuyler',
    xHandle: 'schuyler_dev',
    avatarUrl: 'https://pbs.twimg.com/profile_images/1948085790300364800/tnb8Zu_h_400x400.jpg',
    verified: true,
    personalPages: [{ name: 'X', url: 'https://x.com/schuyler_dev' }],
    projectPages: [],
    bio: 'Perplexity for research, Cursor for coding, Claude Max for heavy lifting.',
  },
]
