export const modelsData = [
  // Anthropic Models
  {
    name: 'Claude 4 Sonnet',
    slug: 'claude-4-sonnet',
    provider: 'Anthropic',
    category: 'reasoning' as const,
    iconUrl: 'https://cdn.prod.website-files.com/6889473510b50328dbb70ae6/68c33859cc6cd903686c66a2_apple-touch-icon.png',
    websiteUrl: 'https://anthropic.com',
    contextWindow: 200000,
    description: 'Most intelligent model with extended thinking capabilities',
    reviewStatus: 'approved' as const,
  },
  {
    name: 'Claude 3.5 Sonnet',
    slug: 'claude-3-5-sonnet',
    provider: 'Anthropic',
    category: 'coding' as const,
    iconUrl: 'https://cdn.prod.website-files.com/6889473510b50328dbb70ae6/68c33859cc6cd903686c66a2_apple-touch-icon.png',
    websiteUrl: 'https://anthropic.com',
    contextWindow: 200000,
    description: 'Fast and capable model optimized for coding tasks',
    reviewStatus: 'approved' as const,
  },
  {
    name: 'Claude 3.5 Haiku',
    slug: 'claude-3-5-haiku',
    provider: 'Anthropic',
    category: 'language' as const,
    iconUrl: 'https://cdn.prod.website-files.com/6889473510b50328dbb70ae6/68c33859cc6cd903686c66a2_apple-touch-icon.png',
    websiteUrl: 'https://anthropic.com',
    contextWindow: 200000,
    description: 'Fast and affordable model for everyday tasks',
    reviewStatus: 'approved' as const,
  },
  // OpenAI Models
  {
    name: 'GPT-4o',
    slug: 'gpt-4o',
    provider: 'OpenAI',
    category: 'language' as const,
    iconUrl: 'https://chatgpt.com/cdn/assets/favicon-180x180-od45eci6.webp',
    websiteUrl: 'https://openai.com',
    contextWindow: 128000,
    description: 'Flagship multimodal model with vision and audio capabilities',
    reviewStatus: 'approved' as const,
  },
  {
    name: 'GPT-4.1',
    slug: 'gpt-4-1',
    provider: 'OpenAI',
    category: 'coding' as const,
    iconUrl: 'https://chatgpt.com/cdn/assets/favicon-180x180-od45eci6.webp',
    websiteUrl: 'https://openai.com',
    contextWindow: 1000000,
    description: 'Latest GPT model optimized for coding with 1M context',
    reviewStatus: 'approved' as const,
  },
  {
    name: 'o3',
    slug: 'o3',
    provider: 'OpenAI',
    category: 'reasoning' as const,
    iconUrl: 'https://chatgpt.com/cdn/assets/favicon-180x180-od45eci6.webp',
    websiteUrl: 'https://openai.com',
    contextWindow: 200000,
    description: 'Advanced reasoning model with chain-of-thought capabilities',
    reviewStatus: 'approved' as const,
  },
  {
    name: 'o4-mini',
    slug: 'o4-mini',
    provider: 'OpenAI',
    category: 'reasoning' as const,
    iconUrl: 'https://chatgpt.com/cdn/assets/favicon-180x180-od45eci6.webp',
    websiteUrl: 'https://openai.com',
    contextWindow: 200000,
    description: 'Fast reasoning model for complex tasks',
    reviewStatus: 'approved' as const,
  },
  // Google Models
  {
    name: 'Gemini 2.5 Pro',
    slug: 'gemini-2-5-pro',
    provider: 'Google',
    category: 'reasoning' as const,
    iconUrl: 'https://www.gstatic.com/lamda/images/gemini_favicon_f069958c85030f9e4.png',
    websiteUrl: 'https://deepmind.google/technologies/gemini/',
    contextWindow: 1000000,
    description: 'Google\'s most capable model with 1M context window',
    reviewStatus: 'approved' as const,
  },
  {
    name: 'Gemini 2.5 Flash',
    slug: 'gemini-2-5-flash',
    provider: 'Google',
    category: 'language' as const,
    iconUrl: 'https://www.gstatic.com/lamda/images/gemini_favicon_f069958c85030f9e4.png',
    websiteUrl: 'https://deepmind.google/technologies/gemini/',
    contextWindow: 1000000,
    description: 'Fast and efficient model for everyday tasks',
    reviewStatus: 'approved' as const,
  },
  // xAI Models
  {
    name: 'Grok 3',
    slug: 'grok-3',
    provider: 'xAI',
    category: 'reasoning' as const,
    iconUrl: 'https://x.ai/favicon.ico',
    websiteUrl: 'https://x.ai',
    contextWindow: 131072,
    description: 'xAI\'s flagship reasoning model',
    reviewStatus: 'approved' as const,
  },
  // Meta Models
  {
    name: 'Llama 4 Maverick',
    slug: 'llama-4-maverick',
    provider: 'Meta',
    category: 'language' as const,
    iconUrl: 'https://llama.meta.com/favicon.ico',
    websiteUrl: 'https://llama.meta.com',
    contextWindow: 1000000,
    description: 'Meta\'s open-weight flagship model',
    reviewStatus: 'approved' as const,
  },
  // Image Models
  {
    name: 'DALL-E 3',
    slug: 'dall-e-3',
    provider: 'OpenAI',
    category: 'image' as const,
    iconUrl: 'https://chatgpt.com/cdn/assets/favicon-180x180-od45eci6.webp',
    websiteUrl: 'https://openai.com/dall-e-3',
    description: 'Advanced image generation model',
    reviewStatus: 'approved' as const,
  },
  {
    name: 'Midjourney v6',
    slug: 'midjourney-v6',
    provider: 'Midjourney',
    category: 'image' as const,
    iconUrl: 'https://www.midjourney.com/favicon.ico',
    websiteUrl: 'https://midjourney.com',
    description: 'High-quality artistic image generation',
    reviewStatus: 'approved' as const,
  },
  {
    name: 'Imagen 3',
    slug: 'imagen-3',
    provider: 'Google',
    category: 'image' as const,
    iconUrl: 'https://www.gstatic.com/lamda/images/gemini_favicon_f069958c85030f9e4.png',
    websiteUrl: 'https://deepmind.google/technologies/imagen-3/',
    description: 'Google\'s latest image generation model',
    reviewStatus: 'approved' as const,
  },
  // Audio Models
  {
    name: 'Whisper',
    slug: 'whisper',
    provider: 'OpenAI',
    category: 'audio' as const,
    iconUrl: 'https://chatgpt.com/cdn/assets/favicon-180x180-od45eci6.webp',
    websiteUrl: 'https://openai.com/research/whisper',
    description: 'Speech-to-text transcription model',
    reviewStatus: 'approved' as const,
  },
  // Video Models
  {
    name: 'Sora',
    slug: 'sora',
    provider: 'OpenAI',
    category: 'video' as const,
    iconUrl: 'https://chatgpt.com/cdn/assets/favicon-180x180-od45eci6.webp',
    websiteUrl: 'https://openai.com/sora',
    description: 'Text-to-video generation model',
    reviewStatus: 'approved' as const,
  },
  {
    name: 'Kling 1.6',
    slug: 'kling-1-6',
    provider: 'Kuaishou',
    category: 'video' as const,
    iconUrl: 'https://klingai.com/favicon.ico',
    websiteUrl: 'https://klingai.com',
    description: 'Advanced video generation model',
    reviewStatus: 'approved' as const,
  },
  // Embedding Models
  {
    name: 'text-embedding-3-large',
    slug: 'text-embedding-3-large',
    provider: 'OpenAI',
    category: 'embedding' as const,
    iconUrl: 'https://chatgpt.com/cdn/assets/favicon-180x180-od45eci6.webp',
    websiteUrl: 'https://openai.com',
    description: 'High-quality text embeddings for semantic search',
    reviewStatus: 'approved' as const,
  },
];
