export const toolsData = [
  {
    name: 'Claude Pro',
    slug: 'claude-pro',
    category: 'thinking',
    iconUrl: 'https://cdn.prod.website-files.com/6889473510b50328dbb70ae6/68c33859cc6cd903686c66a2_apple-touch-icon.png',
    websiteUrl: 'https://claude.ai',
    tiers: [
      { tierId: 'pro', name: 'Pro', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 20, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Claude Max',
    slug: 'claude-max',
    category: 'thinking',
    iconUrl: 'https://cdn.prod.website-files.com/6889473510b50328dbb70ae6/68c33859cc6cd903686c66a2_apple-touch-icon.png',
    websiteUrl: 'https://claude.ai',
    tiers: [
      { tierId: 'max-100', name: 'Max $100', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 100, period: 'month' as const } }, isDefault: true },
      { tierId: 'max-200', name: 'Max $200', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 200, period: 'month' as const } } },
    ],
  },
  {
    name: 'Claude Code',
    slug: 'claude-code',
    category: 'coding',
    iconUrl: 'https://cdn.prod.website-files.com/6889473510b50328dbb70ae6/68c33859cc6cd903686c66a2_apple-touch-icon.png',
    websiteUrl: 'https://claude.ai',
    tiers: [
      { tierId: 'included', name: 'Included with Max', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 0, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'ChatGPT Plus',
    slug: 'chatgpt-plus',
    category: 'text',
    iconUrl: 'https://chatgpt.com/cdn/assets/favicon-180x180-od45eci6.webp',
    websiteUrl: 'https://chatgpt.com',
    tiers: [
      { tierId: 'plus', name: 'Plus', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 20, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Cursor',
    slug: 'cursor',
    category: 'coding',
    iconUrl: 'https://cursor.com/marketing-static/apple-touch-icon.png',
    websiteUrl: 'https://cursor.com',
    tiers: [
      { tierId: 'pro', name: 'Pro', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 20, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Windsurf',
    slug: 'windsurf',
    category: 'coding',
    iconUrl: 'https://windsurf.com/favicon.png',
    websiteUrl: 'https://windsurf.com',
    tiers: [
      { tierId: 'pro', name: 'Pro', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 15, period: 'month' as const } }, isDefault: true },
      { tierId: 'early-adopter', name: 'Early Adopter', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 10, period: 'month' as const } } },
    ],
  },
  {
    name: 'Perplexity',
    slug: 'perplexity',
    category: 'research',
    iconUrl: 'https://framerusercontent.com/images/PFCYmoDJHc11RiF0s6aYcSNaqns.png',
    websiteUrl: 'https://perplexity.ai',
    tiers: [
      { tierId: 'pro', name: 'Pro', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 20, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: "Replit",
    slug: "replit",
    category: "coding",
    iconUrl: "https://replit.com/favicon.ico",
    websiteUrl: "https://replit.com",
    tiers: [{ tierId: "default", name: "Default", pricing: { pricingType: "fixed" as const, fixed: { currency: "USD", amount: 0, period: "month" as const } }, isDefault: true }],
  },
  {
    name: "Bolt",
    slug: "bolt",
    category: "coding",
    iconUrl: "https://bolt.new/favicon.ico",
    websiteUrl: "https://bolt.new",
    tiers: [{ tierId: "default", name: "Default", pricing: { pricingType: "fixed" as const, fixed: { currency: "USD", amount: 0, period: "month" as const } }, isDefault: true }],
  },
  {
    name: "PostHog",
    slug: "posthog",
    category: "analytics",
    iconUrl: "https://posthog.com/favicon.ico",
    websiteUrl: "https://posthog.com",
    tiers: [{ tierId: "default", name: "Default", pricing: { pricingType: "fixed" as const, fixed: { currency: "USD", amount: 0, period: "month" as const } }, isDefault: true }],
  },
  {
    name: 'Wispr Flow',
    slug: 'wispr-flow',
    category: 'voice',
    iconUrl: 'https://cdn.prod.website-files.com/682f84b3838c89f8ff7667db/68d27d1a8a10f417b5644527_flow-wc-v2.png',
    websiteUrl: 'https://wispr.ai',
    tiers: [
      { tierId: 'pro', name: 'Pro', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 12, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Superwhisper',
    slug: 'superwhisper',
    category: 'voice',
    iconUrl: 'https://superwhisper.com/favicon.ico',
    websiteUrl: 'https://superwhisper.com',
    tiers: [
      { tierId: 'pro', name: 'Pro', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 6, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'ChatGPT Workspace',
    slug: 'chatgpt-workspace',
    category: 'ai',
    iconUrl: 'https://cdn.openai.com/favicon.ico',
    websiteUrl: 'https://openai.com/chatgpt/team',
    tiers: [
      { tierId: 'team', name: 'Team', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 60, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Midjourney',
    slug: 'midjourney',
    category: 'image',
    iconUrl: 'https://cdn.midjourney.com/favicon.ico',
    websiteUrl: 'https://midjourney.com',
    tiers: [
      { tierId: 'standard', name: 'Standard', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 24, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Kling.ai',
    slug: 'kling-ai',
    category: 'video',
    iconUrl: 'https://klingai.com/favicon.ico',
    websiteUrl: 'https://klingai.com',
    tiers: [
      { tierId: 'standard', name: 'Standard', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 9, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'X / Grok',
    slug: 'x-grok',
    category: 'ai',
    iconUrl: 'https://x.com/favicon.ico',
    websiteUrl: 'https://x.com',
    tiers: [
      { tierId: 'premium', name: 'Premium', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 8, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Figma',
    slug: 'figma',
    category: 'design',
    iconUrl: 'https://www.figma.com/favicon.ico',
    websiteUrl: 'https://figma.com',
    tiers: [
      { tierId: 'professional', name: 'Professional', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 9 * 65, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Slack',
    slug: 'slack',
    category: 'communication',
    iconUrl: 'https://slack.com/favicon.ico',
    websiteUrl: 'https://slack.com',
    tiers: [
      { tierId: 'pro', name: 'Pro', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 9 * 35, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Envato',
    slug: 'envato',
    category: 'assets',
    iconUrl: 'https://envato.com/favicon.ico',
    websiteUrl: 'https://envato.com',
    tiers: [
      { tierId: 'elements', name: 'Elements', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 16.5, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Adobe Creative Cloud',
    slug: 'adobe-creative-cloud',
    category: 'creative',
    iconUrl: 'https://www.adobe.com/favicon.ico',
    websiteUrl: 'https://adobe.com/creativecloud',
    tiers: [
      { tierId: 'all-apps', name: 'All Apps', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 70, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Unicorn Studio',
    slug: 'unicorn-studio',
    category: '3d',
    iconUrl: 'https://unicorn.studio/favicon.ico',
    websiteUrl: 'https://unicorn.studio',
    tiers: [
      { tierId: 'pro', name: 'Pro', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 18, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Framer',
    slug: 'framer',
    category: 'design',
    iconUrl: 'https://framer.com/favicon.ico',
    websiteUrl: 'https://framer.com',
    tiers: [
      { tierId: 'pro', name: 'Pro', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 45, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Webflow',
    slug: 'webflow',
    category: 'web',
    iconUrl: 'https://webflow.com/favicon.ico',
    websiteUrl: 'https://webflow.com',
    tiers: [
      { tierId: 'cms', name: 'CMS', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 23, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Spline',
    slug: 'spline',
    category: '3d',
    iconUrl: 'https://spline.design/favicon.ico',
    websiteUrl: 'https://spline.design',
    tiers: [
      { tierId: 'super', name: 'Super', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 20, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Google AI Pro',
    slug: 'google-ai-pro',
    category: 'thinking',
    iconUrl: 'https://www.gstatic.com/lamda/images/gemini_favicon_f069958c85030456e93de685481c559f160ea06b.png',
    websiteUrl: 'https://gemini.google.com',
    tiers: [
      { tierId: 'pro', name: 'Pro', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 20, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Google AI Studio',
    slug: 'google-ai-studio',
    category: 'coding',
    iconUrl: 'https://www.gstatic.com/lamda/images/gemini_favicon_f069958c85030456e93de685481c559f160ea06b.png',
    websiteUrl: 'https://aistudio.google.com',
    tiers: [
      { tierId: 'free', name: 'Free', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 0, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Google Antigravity',
    slug: 'google-antigravity',
    category: 'coding',
    iconUrl: 'https://www.gstatic.com/lamda/images/gemini_favicon_f069958c85030456e93de685481c559f160ea06b.png',
    websiteUrl: 'https://idx.google.com',
    tiers: [
      { tierId: 'free', name: 'Free', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 0, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Voice Ink',
    slug: 'voice-ink',
    category: 'voice',
    iconUrl: 'https://tryvoiceink.com/favicon.ico',
    websiteUrl: 'https://tryvoiceink.com',
    tiers: [
      { tierId: 'local', name: 'Local (One-time)', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 0, period: 'one_time' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Codex Extension',
    slug: 'codex-extension',
    category: 'coding',
    iconUrl: 'https://chatgpt.com/cdn/assets/favicon-180x180-od45eci6.webp',
    websiteUrl: 'https://openai.com',
    tiers: [
      { tierId: 'included', name: 'Included with ChatGPT', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 0, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Midjourney',
    slug: 'midjourney',
    category: 'image',
    iconUrl: 'https://www.midjourney.com/favicon.ico',
    websiteUrl: 'https://midjourney.com',
    tiers: [
      { tierId: 'basic', name: 'Basic', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 10, period: 'month' as const } } },
      { tierId: 'standard', name: 'Standard', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 30, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    category: 'voice',
    iconUrl: 'https://elevenlabs.io/apple-icon.png?6592732ab34b1d42',
    websiteUrl: 'https://elevenlabs.io',
    tiers: [
      { tierId: 'starter', name: 'Starter', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 5, period: 'month' as const } } },
      { tierId: 'creator', name: 'Creator', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 22, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Notion AI',
    slug: 'notion-ai',
    category: 'notes',
    iconUrl: 'https://www.notion.com/front-static/logo-ios.png',
    websiteUrl: 'https://notion.so',
    tiers: [
      { tierId: 'ai', name: 'AI Add-on', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 10, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Canva Pro',
    slug: 'canva-pro',
    category: 'creation',
    iconUrl: 'https://static.canva.com/domain-assets/canva/static/images/apple-touch-120x120-1.png',
    websiteUrl: 'https://canva.com',
    tiers: [
      { tierId: 'pro', name: 'Pro', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 15, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Descript',
    slug: 'descript',
    category: 'video',
    iconUrl: 'https://assets-global.website-files.com/5d761d627a6dfa6a5b28ab12/5d761d627a6dfa22d328aba1_Webclip.png',
    websiteUrl: 'https://descript.com',
    tiers: [
      { tierId: 'creator', name: 'Creator', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 12, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Lovable',
    slug: 'lovable',
    category: 'coding',
    iconUrl: 'https://lovable.dev/apple-touch-icon.png',
    websiteUrl: 'https://lovable.dev',
    tiers: [
      { tierId: 'starter', name: 'Starter', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 20, period: 'month' as const } }, isDefault: true },
      { tierId: 'launch', name: 'Launch', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 50, period: 'month' as const } } },
    ],
  },
  {
    name: 'n8n',
    slug: 'n8n',
    category: 'automation',
    iconUrl: 'https://n8n.io/favicon.ico',
    websiteUrl: 'https://n8n.io',
    tiers: [
      { tierId: 'starter', name: 'Starter', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 20, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Zapier',
    slug: 'zapier',
    category: 'automation',
    iconUrl: 'https://zapier.com/favicon.ico',
    websiteUrl: 'https://zapier.com',
    tiers: [
      { tierId: 'starter', name: 'Starter', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 20, period: 'month' as const } }, isDefault: true },
    ],
  },
  {
    name: 'Higgsfield AI',
    slug: 'higgsfield-ai',
    category: 'video',
    iconUrl: 'https://higgsfield.ai/favicon.ico',
    websiteUrl: 'https://higgsfield.ai',
    tiers: [
      { tierId: 'basic', name: 'Basic', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 9, period: 'month' as const } }, isDefault: true },
      { tierId: 'pro', name: 'Pro', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 29, period: 'month' as const } } },
      { tierId: 'ultimate', name: 'Ultimate', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 49, period: 'month' as const } } },
      { tierId: 'creator', name: 'Creator', pricing: { pricingType: 'fixed' as const, fixed: { currency: 'USD', amount: 249, period: 'month' as const } } },
    ],
  },
]
