import {
	BarChart,
	Book,
	Box,
	Brain,
	Code,
	FileText,
	Globe,
	Image,
	MessageSquare,
	Mic,
	Package,
	Palette,
	PenTool,
	Search,
	Sparkles,
	Video,
	Zap,
} from "lucide-react";

export const categoryConfig = {
	coding: {
		icon: Code,
		label: "Coding",
		bgColor: "bg-green-100",
		textColor: "text-green-700",
	},
	creation: {
		icon: Palette,
		label: "Creation",
		bgColor: "bg-purple-100",
		textColor: "text-purple-700",
	},
	notes: {
		icon: Book,
		label: "Notes",
		bgColor: "bg-pink-100",
		textColor: "text-pink-700",
	},
	research: {
		icon: Search,
		label: "Research",
		bgColor: "bg-yellow-100",
		textColor: "text-yellow-700",
	},
	thinking: {
		icon: Brain,
		label: "Thinking",
		bgColor: "bg-blue-100",
		textColor: "text-blue-700",
	},
	voice: {
		icon: Mic,
		label: "Voice",
		bgColor: "bg-orange-100",
		textColor: "text-orange-700",
	},
	automation: {
		icon: Zap,
		label: "Automation",
		bgColor: "bg-red-100",
		textColor: "text-red-700",
	},
	slides: {
		icon: FileText,
		label: "Slides",
		bgColor: "bg-indigo-100",
		textColor: "text-indigo-700",
	},
	video: {
		icon: Video,
		label: "Video",
		bgColor: "bg-teal-100",
		textColor: "text-teal-700",
	},
	image: {
		icon: Image,
		label: "Image",
		bgColor: "bg-cyan-100",
		textColor: "text-cyan-700",
	},
	text: {
		icon: FileText,
		label: "Text",
		bgColor: "bg-gray-100",
		textColor: "text-gray-700",
	},
	ai: {
		icon: Sparkles,
		label: "AI",
		bgColor: "bg-violet-100",
		textColor: "text-violet-700",
	},
	design: {
		icon: PenTool,
		label: "Design",
		bgColor: "bg-fuchsia-100",
		textColor: "text-fuchsia-700",
	},
	communication: {
		icon: MessageSquare,
		label: "Communication",
		bgColor: "bg-sky-100",
		textColor: "text-sky-700",
	},
	assets: {
		icon: Package,
		label: "Assets",
		bgColor: "bg-amber-100",
		textColor: "text-amber-700",
	},
	creative: {
		icon: Palette,
		label: "Creative",
		bgColor: "bg-rose-100",
		textColor: "text-rose-700",
	},
	"3d": {
		icon: Box,
		label: "3D",
		bgColor: "bg-emerald-100",
		textColor: "text-emerald-700",
	},
	web: {
		icon: Globe,
		label: "Web",
		bgColor: "bg-lime-100",
		textColor: "text-lime-700",
	},
	analytics: {
		icon: BarChart,
		label: "Analytics",
		bgColor: "bg-slate-100",
		textColor: "text-slate-700",
	},
} as const;

export type ToolCategory = keyof typeof categoryConfig;
