import {
	Activity,
	BarChart,
	Book,
	Bot,
	Box,
	Brain,
	ClipboardCheck,
	Cloud,
	Image,
	Kanban,
	MessageSquare,
	Mic,
	Monitor,
	Music,
	Package,
	Palette,
	PenTool,
	Presentation,
	Scissors,
	Search,
	Type,
	Video,
	Wand2,
	Zap,
} from "lucide-react";

export const categoryConfig = {
	ide: {
		icon: Monitor,
		label: "IDE",
		bgColor: "bg-green-500/15",
		textColor: "text-green-400",
		borderColor: "border-green-500/40",
	},
	"coding-agent": {
		icon: Bot,
		label: "Coding Agent",
		bgColor: "bg-emerald-500/15",
		textColor: "text-emerald-400",
		borderColor: "border-emerald-500/40",
	},
	"app-builder": {
		icon: Zap,
		label: "App Builder",
		bgColor: "bg-lime-500/15",
		textColor: "text-lime-400",
		borderColor: "border-lime-500/40",
	},
	reasoning: {
		icon: Brain,
		label: "Reasoning",
		bgColor: "bg-blue-500/15",
		textColor: "text-blue-400",
		borderColor: "border-blue-500/40",
	},
	research: {
		icon: Search,
		label: "Research",
		bgColor: "bg-yellow-500/15",
		textColor: "text-yellow-400",
		borderColor: "border-yellow-500/40",
	},
	"image-gen": {
		icon: Image,
		label: "Image Gen",
		bgColor: "bg-cyan-500/15",
		textColor: "text-cyan-400",
		borderColor: "border-cyan-500/40",
	},
	"video-gen": {
		icon: Video,
		label: "Video Gen",
		bgColor: "bg-teal-500/15",
		textColor: "text-teal-400",
		borderColor: "border-teal-500/40",
	},
	"video-editing": {
		icon: Scissors,
		label: "Video Editing",
		bgColor: "bg-indigo-500/15",
		textColor: "text-indigo-400",
		borderColor: "border-indigo-500/40",
	},
	dictation: {
		icon: Mic,
		label: "Dictation",
		bgColor: "bg-orange-500/15",
		textColor: "text-orange-400",
		borderColor: "border-orange-500/40",
	},
	"voice-gen": {
		icon: Wand2,
		label: "Voice Gen",
		bgColor: "bg-purple-500/15",
		textColor: "text-purple-400",
		borderColor: "border-purple-500/40",
	},
	design: {
		icon: PenTool,
		label: "Design",
		bgColor: "bg-fuchsia-500/15",
		textColor: "text-fuchsia-400",
		borderColor: "border-fuchsia-500/40",
	},
	"3d": {
		icon: Box,
		label: "3D",
		bgColor: "bg-sky-500/15",
		textColor: "text-sky-400",
		borderColor: "border-sky-500/40",
	},
	"creative-suite": {
		icon: Palette,
		label: "Creative Suite",
		bgColor: "bg-rose-500/15",
		textColor: "text-rose-400",
		borderColor: "border-rose-500/40",
	},
	assets: {
		icon: Package,
		label: "Assets",
		bgColor: "bg-amber-500/15",
		textColor: "text-amber-400",
		borderColor: "border-amber-500/40",
	},
	notes: {
		icon: Book,
		label: "Notes",
		bgColor: "bg-pink-500/15",
		textColor: "text-pink-400",
		borderColor: "border-pink-500/40",
	},
	communication: {
		icon: MessageSquare,
		label: "Communication",
		bgColor: "bg-gray-500/15",
		textColor: "text-gray-400",
		borderColor: "border-gray-500/40",
	},
	automation: {
		icon: Zap,
		label: "Automation",
		bgColor: "bg-red-500/15",
		textColor: "text-red-400",
		borderColor: "border-red-500/40",
	},
	analytics: {
		icon: BarChart,
		label: "Analytics",
		bgColor: "bg-slate-500/15",
		textColor: "text-slate-400",
		borderColor: "border-slate-500/40",
	},
	"code-review": {
		icon: ClipboardCheck,
		label: "Code Review",
		bgColor: "bg-violet-500/15",
		textColor: "text-violet-400",
		borderColor: "border-violet-500/40",
	},
	writing: {
		icon: Type,
		label: "Writing",
		bgColor: "bg-stone-500/15",
		textColor: "text-stone-400",
		borderColor: "border-stone-500/40",
	},
	"music-gen": {
		icon: Music,
		label: "Music Gen",
		bgColor: "bg-fuchsia-600/15",
		textColor: "text-fuchsia-300",
		borderColor: "border-fuchsia-600/40",
	},
	deployment: {
		icon: Cloud,
		label: "Deployment",
		bgColor: "bg-sky-600/15",
		textColor: "text-sky-300",
		borderColor: "border-sky-600/40",
	},
	monitoring: {
		icon: Activity,
		label: "Monitoring",
		bgColor: "bg-rose-600/15",
		textColor: "text-rose-300",
		borderColor: "border-rose-600/40",
	},
	"project-management": {
		icon: Kanban,
		label: "Project Management",
		bgColor: "bg-blue-600/15",
		textColor: "text-blue-300",
		borderColor: "border-blue-600/40",
	},
	presentation: {
		icon: Presentation,
		label: "Presentation",
		bgColor: "bg-amber-600/15",
		textColor: "text-amber-300",
		borderColor: "border-amber-600/40",
	},
} as const;

export type ToolCategory = keyof typeof categoryConfig;
