import { describe, expect, it, vi } from "vitest";
import {
	BUILTIN_TOOLS,
	BUNDLED_SYNC_CONFIG,
	EMPTY_OPT_INS,
	filterAtoms,
	loadSyncConfig,
	pluginGroup,
} from "./allowlist.js";
import { BUNDLED_CURATED_ALLOWLIST } from "./bundled-allowlist.js";

const jsonResponse = (body: unknown, status = 200): Response =>
	new Response(JSON.stringify(body), {
		status,
		headers: { "Content-Type": "application/json" },
	});

const GOOD_BODY = {
	allowlist: {
		mcpServers: ["github", "linear"],
		skills: ["grilling"],
		subagents: ["Explore"],
		slashCommands: ["clear"],
	},
	publishCost: true,
};

describe("BUILTIN_TOOLS", () => {
	it("covers every tool name observed in the real corpus", () => {
		// Measured on 235,961 records: these 22 names were the entire built-in
		// surface actually exercised. A miss here is a name silently withheld.
		const observed = [
			"Agent",
			"AskUserQuestion",
			"Bash",
			"Edit",
			"Glob",
			"Grep",
			"Monitor",
			"PushNotification",
			"Read",
			"ScheduleWakeup",
			"SendMessage",
			"SendUserFile",
			"Skill",
			"TaskCreate",
			"TaskGet",
			"TaskOutput",
			"TaskStop",
			"TaskUpdate",
			"ToolSearch",
			"WebFetch",
			"WebSearch",
			"Write",
		];
		for (const name of observed) expect(BUILTIN_TOOLS.has(name)).toBe(true);
	});

	it("is a literal set, not a pattern — a plausible fake is not a member", () => {
		expect(BUILTIN_TOOLS.has("ReadFile")).toBe(false);
		expect(BUILTIN_TOOLS.has("BashPlus")).toBe(false);
		expect(BUILTIN_TOOLS.has("bash")).toBe(false); // case-sensitive
	});
});

/** Curated-only sets, the state before any name is ticked. */
const sets = (curated: string[], optIns: string[] = []) => ({
	publishable: new Set([...curated, ...optIns]),
	curated: new Set(curated),
});

describe("filterAtoms", () => {
	it("keeps allowlisted atoms and counts distinct withheld names", () => {
		const result = filterAtoms(
			[
				{ name: "github", count: 10 },
				{ name: "acme-internal", count: 99 },
				{ name: "also-private", count: 1 },
			],
			sets(["github"]),
		);
		expect(result.allowed).toEqual([{ name: "github", count: 10 }]);
		expect(result.withheld).toBe(2);
	});

	it("counts names, not calls, so withheld usage volume stays hidden", () => {
		const result = filterAtoms([{ name: "private", count: 100_000 }], sets([]));
		expect(result.withheld).toBe(1);
	});

	it("orders by count descending, then name, for a stable payload", () => {
		const result = filterAtoms(
			[
				{ name: "b", count: 5 },
				{ name: "a", count: 5 },
				{ name: "c", count: 9 },
			],
			sets(["a", "b", "c"]),
		);
		expect(result.allowed.map((a) => a.name)).toEqual(["c", "a", "b"]);
	});

	it("hands back every kept-private name, so the gate can offer it as a tick", () => {
		// #42 decision 1: coverage comes from the user ticking names, and the gate
		// cannot offer what the analyzer does not return. A count alone was enough
		// for the payload and is not enough for the review list.
		const result = filterAtoms(
			[
				{ name: "github", count: 10 },
				{ name: "alp-river:crossfire", count: 7 },
				{ name: "acme-internal", count: 99 },
			],
			sets(["github"]),
		);
		expect(result.keptPrivate).toEqual([
			{ name: "acme-internal", count: 99, group: null },
			{ name: "alp-river:crossfire", count: 7, group: "alp-river" },
		]);
	});

	it("publishes a name the owner ticked, verbatim", () => {
		const result = filterAtoms(
			[{ name: "alp-river:crossfire", count: 7 }],
			sets([], ["alp-river:crossfire"]),
		);
		expect(result.allowed).toEqual([{ name: "alp-river:crossfire", count: 7 }]);
		expect(result.withheld).toBe(0);
	});

	it("keeps a name private when only a sibling in its plugin was ticked", () => {
		// A tick is a name, never a pattern (#42 decision 3): ticking one
		// `alp-river` subagent grants nothing to the next one written.
		const result = filterAtoms(
			[
				{ name: "alp-river:crossfire", count: 7 },
				{ name: "alp-river:acme-billing-migration", count: 3 },
			],
			sets([], ["alp-river:crossfire"]),
		);
		expect(result.allowed.map((a) => a.name)).toEqual(["alp-river:crossfire"]);
		expect(result.keptPrivate.map((a) => a.name)).toEqual([
			"alp-river:acme-billing-migration",
		]);
	});
});

describe("plugin-wrapper normalization (#42 decision 5)", () => {
	// The three rows of the decision's own table. `plugin_<plugin>_<server>` is
	// generated by Claude Code, not typed by the user.
	it.each([
		["plugin_chrome-devtools-mcp_chrome-devtools", "chrome-devtools"],
		["plugin_acme-secret_stripe", "stripe"],
	])("publishes %s as its curated inner segment", (observed, published) => {
		const result = filterAtoms(
			[{ name: observed, count: 4 }],
			sets(["chrome-devtools", "stripe"]),
		);
		expect(result.allowed).toEqual([{ name: published, count: 4 }]);
		expect(result.keptPrivate).toEqual([]);
	});

	it("emits nothing when the inner segment is not curated", () => {
		// Row three of the table: the raw name falls through to the review list,
		// which is what bounds a normalization bug to an already-vetted set.
		const result = filterAtoms(
			[{ name: "plugin_acme-internal_billing", count: 4 }],
			sets(["chrome-devtools", "stripe"]),
		);
		expect(result.allowed).toEqual([]);
		expect(result.keptPrivate).toEqual([
			{
				name: "plugin_acme-internal_billing",
				count: 4,
				group: "acme-internal",
			},
		]);
	});

	it("does not let an opt-in be the target of normalization", () => {
		// Normalization may only ever emit a string that is already CURATED. An
		// opt-in is a name the user saw and ticked; the inner segment is neither.
		const result = filterAtoms(
			[{ name: "plugin_acme-internal_billing", count: 4 }],
			sets([], ["billing"]),
		);
		expect(result.allowed).toEqual([]);
		expect(result.withheld).toBe(1);
	});

	it("publishes the raw wrapper when the owner ticked that exact string", () => {
		// Consent is to the string as rendered at the gate — including the plugin
		// name it carries.
		const result = filterAtoms(
			[{ name: "plugin_acme-internal_billing", count: 4 }],
			sets([], ["plugin_acme-internal_billing"]),
		);
		expect(result.allowed).toEqual([
			{ name: "plugin_acme-internal_billing", count: 4 },
		]);
	});

	it("merges two observed names that publish under one", () => {
		// A plugin-provided server and a directly configured one both land on
		// `chrome-devtools`; two rows with one name would double-count it.
		const result = filterAtoms(
			[
				{ name: "chrome-devtools", count: 3 },
				{ name: "plugin_chrome-devtools-mcp_chrome-devtools", count: 4 },
			],
			sets(["chrome-devtools"]),
		);
		expect(result.allowed).toEqual([{ name: "chrome-devtools", count: 7 }]);
	});

	it("keeps a wrapper private when the plugin name carries an underscore", () => {
		// The split takes the first underscore-free segment, so this one splits
		// wrong — and fails in the same direction every other miss does.
		const result = filterAtoms(
			[{ name: "plugin_acme_secret_stripe", count: 4 }],
			sets(["stripe"]),
		);
		expect(result.allowed).toEqual([]);
		expect(result.withheld).toBe(1);
	});
});

describe("pluginGroup", () => {
	it("reads both plugin conventions, and nothing else", () => {
		expect(pluginGroup("plugin_chrome-devtools-mcp_chrome-devtools")).toBe(
			"chrome-devtools-mcp",
		);
		expect(pluginGroup("alp-river:crossfire")).toBe("alp-river");
		expect(pluginGroup("grilling")).toBeNull();
		expect(pluginGroup("acme-internal")).toBeNull();
	});
});

describe("loadSyncConfig", () => {
	it("uses the fetched list when the endpoint answers", async () => {
		const fetchImpl = vi.fn().mockResolvedValue(jsonResponse(GOOD_BODY));
		const loaded = await loadSyncConfig({
			baseUrl: "https://aistack.to",
			fetchImpl: fetchImpl as unknown as typeof fetch,
		});
		expect(fetchImpl).toHaveBeenCalledWith(
			"https://aistack.to/api/sync-config",
			expect.objectContaining({ headers: { Accept: "application/json" } }),
		);
		expect(loaded.source).toBe("fetched");
		expect(loaded.config.allowlist.mcpServers).toEqual(["github", "linear"]);
		expect(loaded.config.publishCost).toBe(true);
	});

	it("falls back to the bundled copy on a network error, without throwing", async () => {
		// A bundled-only list is, for a user whose plugin never auto-updates,
		// frozen forever — but an unreachable aistack must never break the scan.
		const loaded = await loadSyncConfig({
			baseUrl: "https://aistack.to",
			fetchImpl: (() =>
				Promise.reject(new Error("ENOTFOUND"))) as unknown as typeof fetch,
		});
		expect(loaded.source).toBe("bundled");
		expect(loaded.error).toContain("ENOTFOUND");
		expect(loaded.config).toBe(BUNDLED_SYNC_CONFIG);
	});

	it("falls back on a non-2xx status", async () => {
		const loaded = await loadSyncConfig({
			baseUrl: "https://aistack.to",
			fetchImpl: (() =>
				Promise.resolve(jsonResponse({}, 503))) as unknown as typeof fetch,
		});
		expect(loaded.source).toBe("bundled");
		expect(loaded.error).toContain("503");
	});

	it("falls back on a body that is not the expected shape", async () => {
		for (const body of [null, [], "nope", { publishCost: true }]) {
			const loaded = await loadSyncConfig({
				baseUrl: "https://aistack.to",
				fetchImpl: (() =>
					Promise.resolve(jsonResponse(body))) as unknown as typeof fetch,
			});
			expect(loaded.source).toBe("bundled");
		}
	});

	it("withholds cost by default when the config could not be read", () => {
		// A preference we cannot read fails closed to the option that transmits
		// less; a snapshot is immutable, so over-publishing is unrecoverable.
		expect(BUNDLED_SYNC_CONFIG.publishCost).toBe(false);
	});

	it("requires publishCost to be exactly true", async () => {
		const loaded = await loadSyncConfig({
			baseUrl: "https://aistack.to",
			fetchImpl: (() =>
				Promise.resolve(
					jsonResponse({ ...GOOD_BODY, publishCost: "yes" }),
				)) as unknown as typeof fetch,
		});
		expect(loaded.source).toBe("fetched");
		expect(loaded.config.publishCost).toBe(false);
	});

	it("requires reviewKeptPrivate to be exactly true, and defaults it off", async () => {
		// The switch is ON server-side by default, so the only way it reads false
		// here is a config the machine could not read. That direction keeps the
		// names on the machine and costs the owner one retry.
		expect(BUNDLED_SYNC_CONFIG.reviewKeptPrivate).toBe(false);

		const read = async (value: unknown) => {
			const loaded = await loadSyncConfig({
				baseUrl: "https://aistack.to",
				fetchImpl: (() =>
					Promise.resolve(
						jsonResponse({ ...GOOD_BODY, reviewKeptPrivate: value }),
					)) as unknown as typeof fetch,
			});
			return loaded.config.reviewKeptPrivate;
		};
		expect(await read(true)).toBe(true);
		expect(await read("yes")).toBe(false);
		expect(await read(undefined)).toBe(false);
	});

	it("drops names from the server that fail the charset or length bound", async () => {
		// A server-supplied list can widen what publishes — that is accepted,
		// because the gate renders every name. It cannot smuggle a control
		// character, a wildcard, or an unbounded string.
		const loaded = await loadSyncConfig({
			baseUrl: "https://aistack.to",
			fetchImpl: (() =>
				Promise.resolve(
					jsonResponse({
						allowlist: {
							mcpServers: [
								"github",
								"*",
								"bad‮name",
								"x".repeat(200),
								"",
								42,
								null,
							],
							skills: "not-an-array",
							subagents: [],
							slashCommands: [],
						},
						publishCost: true,
					}),
				)) as unknown as typeof fetch,
		});
		expect(loaded.config.allowlist.mcpServers).toEqual(["github"]);
		expect(loaded.config.allowlist.skills).toEqual([]);
	});

	it("reads the per-stack opt-ins the authenticated half carries", async () => {
		const loaded = await loadSyncConfig({
			baseUrl: "https://aistack.to",
			fetchImpl: (() =>
				Promise.resolve(
					jsonResponse({
						...GOOD_BODY,
						optIns: {
							builtinTools: [],
							mcpServers: ["plugin_acme-internal_billing"],
							skills: ["alp-river:crossfire"],
							subagents: ["(default)"],
							slashCommands: [],
						},
					}),
				)) as unknown as typeof fetch,
		});
		expect(loaded.config.optIns.skills).toEqual(["alp-river:crossfire"]);
		// A ticked name is the USER's string, so the curated list's conventional
		// charset is the wrong bar — parentheses are a legitimate name.
		expect(loaded.config.optIns.subagents).toEqual(["(default)"]);
	});

	it("reverts to no opt-ins when the response carries none", async () => {
		// The anonymous response and a token bound to no stack both look like
		// this. Both mean: publish no user-chosen names.
		const loaded = await loadSyncConfig({
			baseUrl: "https://aistack.to",
			fetchImpl: (() =>
				Promise.resolve(jsonResponse(GOOD_BODY))) as unknown as typeof fetch,
		});
		expect(loaded.config.optIns).toEqual(EMPTY_OPT_INS);
	});

	it("drops an opt-in that cannot be rendered safely", async () => {
		const loaded = await loadSyncConfig({
			baseUrl: "https://aistack.to",
			fetchImpl: (() =>
				Promise.resolve(
					jsonResponse({
						...GOOD_BODY,
						optIns: {
							...EMPTY_OPT_INS,
							skills: ["ok-name", "bidi‮name", "z".repeat(200), "  ", 7],
						},
					}),
				)) as unknown as typeof fetch,
		});
		expect(loaded.config.optIns.skills).toEqual(["ok-name"]);
	});

	it("carries no opt-ins in the bundled fallback", async () => {
		// The intended failure direction of #42 decision 2: losing the network
		// publishes LESS. Every ticked name reverts to kept-private.
		const loaded = await loadSyncConfig({
			baseUrl: "https://aistack.to",
			fetchImpl: (() =>
				Promise.reject(new Error("ENOTFOUND"))) as unknown as typeof fetch,
		});
		expect(loaded.config.optIns).toEqual(EMPTY_OPT_INS);
		expect(BUNDLED_SYNC_CONFIG.optIns).toEqual(EMPTY_OPT_INS);
	});

	it("bounds the request with a timeout signal", async () => {
		const fetchImpl = vi.fn().mockResolvedValue(jsonResponse(GOOD_BODY));
		await loadSyncConfig({
			baseUrl: "https://aistack.to",
			fetchImpl: fetchImpl as unknown as typeof fetch,
			timeoutMs: 1_234,
		});
		const init = fetchImpl.mock.calls[0][1] as RequestInit;
		expect(init.signal).toBeInstanceOf(AbortSignal);
	});
});

describe("bundled curated allowlist", () => {
	it("holds only public artifacts — no author-specific plugin names", () => {
		const all = [
			...BUNDLED_CURATED_ALLOWLIST.mcpServers,
			...BUNDLED_CURATED_ALLOWLIST.skills,
			...BUNDLED_CURATED_ALLOWLIST.subagents,
			...BUNDLED_CURATED_ALLOWLIST.slashCommands,
		];
		// The owner's own plugin dominates their corpus and is deliberately NOT
		// seeded here: curation is server-side work (#38).
		expect(all.some((n) => n.startsWith("alp-river:"))).toBe(false);
	});

	it("keeps every entry inside the same charset the fetched list must satisfy", () => {
		const ok = /^[A-Za-z0-9][A-Za-z0-9 ._:@/-]{0,63}$|^\(default\)$/;
		for (const name of [
			...BUNDLED_CURATED_ALLOWLIST.mcpServers,
			...BUNDLED_CURATED_ALLOWLIST.skills,
			...BUNDLED_CURATED_ALLOWLIST.subagents,
			...BUNDLED_CURATED_ALLOWLIST.slashCommands,
		]) {
			expect(name).toMatch(ok);
		}
	});
});

describe("the destination stack on the authenticated half (#41)", () => {
	const jsonResponse = (body: unknown, status = 200) =>
		new Response(JSON.stringify(body), { status });

	it("sends the bearer when a token is given, and never otherwise", async () => {
		const fetchImpl = vi.fn().mockResolvedValue(jsonResponse(GOOD_BODY));
		await loadSyncConfig({
			baseUrl: "https://aistack.to",
			token: "tok_1",
			fetchImpl: fetchImpl as unknown as typeof fetch,
		});
		expect(fetchImpl).toHaveBeenCalledWith(
			"https://aistack.to/api/sync-config",
			expect.objectContaining({
				headers: expect.objectContaining({ Authorization: "Bearer tok_1" }),
			}),
		);
		fetchImpl.mockClear();
		await loadSyncConfig({
			baseUrl: "https://aistack.to",
			fetchImpl: fetchImpl as unknown as typeof fetch,
		});
		const headers = (fetchImpl.mock.calls[0][1] as RequestInit)
			.headers as Record<string, string>;
		expect(headers.Authorization).toBeUndefined();
	});

	it("reads a well-formed stack and fails closed on anything else", async () => {
		const load = async (stack: unknown) => {
			const loaded = await loadSyncConfig({
				baseUrl: "https://aistack.to",
				fetchImpl: (() =>
					Promise.resolve(
						jsonResponse({ ...GOOD_BODY, stack }),
					)) as unknown as typeof fetch,
			});
			return loaded.config.stack;
		};
		expect(await load({ name: "My Stack", slug: "my-stack" })).toEqual({
			name: "My Stack",
			slug: "my-stack",
		});
		// Absent, null, or malformed all read as "no destination" — and the
		// gate refuses to publish without one.
		expect(await load(undefined)).toBeNull();
		expect(await load(null)).toBeNull();
		expect(await load({ name: "x" })).toBeNull();
		expect(await load({ name: "x", slug: "Bad Slug!" })).toBeNull();
		expect(await load({ name: "x‮gnp.exe", slug: "ok" })).toBeNull();
	});

	it("the bundled fallback carries no stack", () => {
		expect(BUNDLED_SYNC_CONFIG.stack).toBeNull();
	});
});
