#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.."
ENV_FILE="$PWD/.env.discord-prototype.local"
umask 077
if [[ ! -t 0 ]]; then
  say "Run this setup in your own terminal so you can enter test-app credentials."
  exit 1
fi
banner "AI Stack: live Discord prototype"

stage "Create or select a separate test app"
open_url "https://discord.com/developers/applications"
step "Create a new application named AI Stack Prototype, or open your existing test app."
step "Use a separate app from production. Open General Information."
ask DISCORD_PROTOTYPE_APP_ID "Application ID:"
[[ "$DISCORD_PROTOTYPE_APP_ID" =~ ^[0-9]{16,22}$ ]] || { warn "Application ID must be numeric."; exit 1; }
ask DISCORD_PROTOTYPE_PUBLIC_KEY "Public Key:"
[[ "$DISCORD_PROTOTYPE_PUBLIC_KEY" =~ ^[a-fA-F0-9]{64}$ ]] || { warn "Public Key must be 64 hex characters."; exit 1; }
write_env DISCORD_PROTOTYPE_APP_ID "$DISCORD_PROTOTYPE_APP_ID"
write_env DISCORD_PROTOTYPE_PUBLIC_KEY "$DISCORD_PROTOTYPE_PUBLIC_KEY"
pause "Saved. Press Enter for the bot token."

stage "Save the test bot token"
open_url "https://discord.com/developers/applications/$DISCORD_PROTOTYPE_APP_ID/bot"
step "Copy the test bot token. If it is unavailable, use Reset Token on this test app."
step "Leave all Privileged Gateway Intents off."
ask_secret DISCORD_PROTOTYPE_BOT_TOKEN "Test bot token (hidden):"
[[ "$DISCORD_PROTOTYPE_BOT_TOKEN" =~ ^[A-Za-z0-9._-]+$ ]] || { warn "Enter a nonempty Discord bot token."; exit 1; }
write_env DISCORD_PROTOTYPE_BOT_TOKEN "$DISCORD_PROTOTYPE_BOT_TOKEN"
chmod 600 "$ENV_FILE"
note "Only local command registration uses this token. Never paste it into chat."
pause "Press Enter to install the test app."

stage "Install in a test server"
open_url "https://discord.com/developers/applications/$DISCORD_PROTOTYPE_APP_ID/installation"
step "Ensure Guild Install is enabled for this test app."
pause "Press Enter to open its server installation link."
open_url "https://discord.com/oauth2/authorize?client_id=$DISCORD_PROTOTYPE_APP_ID&scope=bot%20applications.commands&permissions=51200&integration_type=0"
step "Choose a quiet test server you manage and authorize the app."
step "In Discord, enable User Settings > Advanced > Developer Mode."
step "Right-click that server and choose Copy Server ID."
ask DISCORD_PROTOTYPE_GUILD_ID "Test server ID:"
[[ "$DISCORD_PROTOTYPE_GUILD_ID" =~ ^[0-9]{16,22}$ ]] || { warn "Server ID must be numeric."; exit 1; }
write_env DISCORD_PROTOTYPE_GUILD_ID "$DISCORD_PROTOTYPE_GUILD_ID"
pause "Press Enter to connect the local endpoint."

stage "Start the endpoint and HTTPS tunnel"
step "In another terminal at the repo root, run: pnpm discord:prototype"
step "In a second terminal, run: ngrok http 3020"
note "ngrok is installed here and its configuration validates. Leave both processes running."
step "Copy the HTTPS forwarding URL that ngrok prints."
ask DISCORD_PROTOTYPE_PUBLIC_URL "HTTPS URL (without /interactions):"
DISCORD_PROTOTYPE_PUBLIC_URL="${DISCORD_PROTOTYPE_PUBLIC_URL%/}"
[[ "$DISCORD_PROTOTYPE_PUBLIC_URL" =~ ^https://[A-Za-z0-9.-]+$ ]] || { warn "Enter an HTTPS origin such as https://example.ngrok-free.app."; exit 1; }
write_env DISCORD_PROTOTYPE_PUBLIC_URL "$DISCORD_PROTOTYPE_PUBLIC_URL"
open_url "https://discord.com/developers/applications/$DISCORD_PROTOTYPE_APP_ID/information"
step "Set Interactions Endpoint URL to: $DISCORD_PROTOTYPE_PUBLIC_URL/interactions"
step "Save Changes. Discord must accept the signature and PING verification."
pause "Press Enter after Discord accepts the endpoint."

stage "Register and try the five commands"
pnpm discord:prototype register
say "In your test server, try /tokens, /cost, /context, /harness, and /compare."
step "Try /compare person:ali and select alice from autocomplete."
step "Click Compare on /tokens, choose a person, then change the range."
step "Try Search people and Custom days. Check that the same answer updates."
step "Have a second account click a control. Only that account should see the rejection."
note "All values are synthetic. No production functions, global commands, or database rows changed."
note "Cleanup: pnpm discord:prototype unregister, then stop the local server and ngrok."
pause "Press Enter to finish setup."
finish
