/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaitlistLookupIdRouteImport } from './routes/waitlist.$lookupId'
import { Route as StacksNewRouteImport } from './routes/stacks.new'
import { Route as StacksSlugRouteImport } from './routes/stacks.$slug'
import { Route as StacksSlugEditRouteImport } from './routes/stacks.$slug_.edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistLookupIdRoute = WaitlistLookupIdRouteImport.update({
  id: '/waitlist/$lookupId',
  path: '/waitlist/$lookupId',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksNewRoute = StacksNewRouteImport.update({
  id: '/stacks/new',
  path: '/stacks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksSlugRoute = StacksSlugRouteImport.update({
  id: '/stacks/$slug',
  path: '/stacks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksSlugEditRoute = StacksSlugEditRouteImport.update({
  id: '/stacks/$slug_/edit',
  path: '/stacks/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/stacks/$slug': typeof StacksSlugRoute
  '/stacks/new': typeof StacksNewRoute
  '/waitlist/$lookupId': typeof WaitlistLookupIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/stacks/$slug/edit': typeof StacksSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/stacks/$slug': typeof StacksSlugRoute
  '/stacks/new': typeof StacksNewRoute
  '/waitlist/$lookupId': typeof WaitlistLookupIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/stacks/$slug/edit': typeof StacksSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/stacks/$slug': typeof StacksSlugRoute
  '/stacks/new': typeof StacksNewRoute
  '/waitlist/$lookupId': typeof WaitlistLookupIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/stacks/$slug_/edit': typeof StacksSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-callback'
    | '/login'
    | '/test'
    | '/stacks/$slug'
    | '/stacks/new'
    | '/waitlist/$lookupId'
    | '/api/auth/$'
    | '/stacks/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-callback'
    | '/login'
    | '/test'
    | '/stacks/$slug'
    | '/stacks/new'
    | '/waitlist/$lookupId'
    | '/api/auth/$'
    | '/stacks/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/auth-callback'
    | '/login'
    | '/test'
    | '/stacks/$slug'
    | '/stacks/new'
    | '/waitlist/$lookupId'
    | '/api/auth/$'
    | '/stacks/$slug_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  LoginRoute: typeof LoginRoute
  TestRoute: typeof TestRoute
  StacksSlugRoute: typeof StacksSlugRoute
  StacksNewRoute: typeof StacksNewRoute
  WaitlistLookupIdRoute: typeof WaitlistLookupIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  StacksSlugEditRoute: typeof StacksSlugEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/$lookupId': {
      id: '/waitlist/$lookupId'
      path: '/waitlist/$lookupId'
      fullPath: '/waitlist/$lookupId'
      preLoaderRoute: typeof WaitlistLookupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/new': {
      id: '/stacks/new'
      path: '/stacks/new'
      fullPath: '/stacks/new'
      preLoaderRoute: typeof StacksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$slug': {
      id: '/stacks/$slug'
      path: '/stacks/$slug'
      fullPath: '/stacks/$slug'
      preLoaderRoute: typeof StacksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$slug_/edit': {
      id: '/stacks/$slug_/edit'
      path: '/stacks/$slug/edit'
      fullPath: '/stacks/$slug/edit'
      preLoaderRoute: typeof StacksSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  LoginRoute: LoginRoute,
  TestRoute: TestRoute,
  StacksSlugRoute: StacksSlugRoute,
  StacksNewRoute: StacksNewRoute,
  WaitlistLookupIdRoute: WaitlistLookupIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  StacksSlugEditRoute: StacksSlugEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
