/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TestRouteImport } from './routes/test'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SigninPublishRouteImport } from './routes/signin-publish'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CreatorRouteImport } from './routes/$creator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StacksIndexRouteImport } from './routes/stacks.index'
import { Route as WaitlistLookupIdRouteImport } from './routes/waitlist.$lookupId'
import { Route as ToolsNewRouteImport } from './routes/tools_.new'
import { Route as StacksNewRouteImport } from './routes/stacks.new'
import { Route as StacksSlugRouteImport } from './routes/stacks.$slug'
import { Route as SettingsMachinesRouteImport } from './routes/settings.machines'
import { Route as SettingsAnalyticsRouteImport } from './routes/settings.analytics'
import { Route as PrototypeViewsStackRouteImport } from './routes/prototype.views-stack'
import { Route as PrototypeViewsEntryRouteImport } from './routes/prototype.views-entry'
import { Route as PrototypeViewsRouteImport } from './routes/prototype.views'
import { Route as PrototypeFreshnessRouteImport } from './routes/prototype.freshness'
import { Route as CliAuthRouteImport } from './routes/cli.auth'
import { Route as ApiSyncConfigRouteImport } from './routes/api.sync-config'
import { Route as AdminIconsRouteImport } from './routes/admin_.icons'
import { Route as StacksSlugEditRouteImport } from './routes/stacks.$slug_.edit'
import { Route as StacksSlugChangesRouteImport } from './routes/stacks.$slug_.changes'
import { Route as ApiStacksSlugRouteImport } from './routes/api.stacks.$slug'
import { Route as ApiIconsFromUrlRouteImport } from './routes/api.icons.from-url'
import { Route as ApiCliSyncRouteImport } from './routes/api.cli.sync'
import { Route as ApiCliStacksRouteImport } from './routes/api.cli.stacks'
import { Route as ApiCliAutoSyncRouteImport } from './routes/api.cli.auto-sync'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiOgStackSlugRouteImport } from './routes/api.og.stack.$slug'
import { Route as ApiCliStacksCollectRouteImport } from './routes/api.cli.stacks.collect'
import { Route as ApiCliAuthStartRouteImport } from './routes/api.cli.auth.start'
import { Route as ApiCliAuthPollRouteImport } from './routes/api.cli.auth.poll'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninPublishRoute = SigninPublishRouteImport.update({
  id: '/signin-publish',
  path: '/signin-publish',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/$creator',
  path: '/$creator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksIndexRoute = StacksIndexRouteImport.update({
  id: '/stacks/',
  path: '/stacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistLookupIdRoute = WaitlistLookupIdRouteImport.update({
  id: '/waitlist/$lookupId',
  path: '/waitlist/$lookupId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsNewRoute = ToolsNewRouteImport.update({
  id: '/tools_/new',
  path: '/tools/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksNewRoute = StacksNewRouteImport.update({
  id: '/stacks/new',
  path: '/stacks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksSlugRoute = StacksSlugRouteImport.update({
  id: '/stacks/$slug',
  path: '/stacks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMachinesRoute = SettingsMachinesRouteImport.update({
  id: '/settings/machines',
  path: '/settings/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAnalyticsRoute = SettingsAnalyticsRouteImport.update({
  id: '/settings/analytics',
  path: '/settings/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeViewsStackRoute = PrototypeViewsStackRouteImport.update({
  id: '/prototype/views-stack',
  path: '/prototype/views-stack',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeViewsEntryRoute = PrototypeViewsEntryRouteImport.update({
  id: '/prototype/views-entry',
  path: '/prototype/views-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeViewsRoute = PrototypeViewsRouteImport.update({
  id: '/prototype/views',
  path: '/prototype/views',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeFreshnessRoute = PrototypeFreshnessRouteImport.update({
  id: '/prototype/freshness',
  path: '/prototype/freshness',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthRoute = CliAuthRouteImport.update({
  id: '/cli/auth',
  path: '/cli/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncConfigRoute = ApiSyncConfigRouteImport.update({
  id: '/api/sync-config',
  path: '/api/sync-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIconsRoute = AdminIconsRouteImport.update({
  id: '/admin_/icons',
  path: '/admin/icons',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksSlugEditRoute = StacksSlugEditRouteImport.update({
  id: '/stacks/$slug_/edit',
  path: '/stacks/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksSlugChangesRoute = StacksSlugChangesRouteImport.update({
  id: '/stacks/$slug_/changes',
  path: '/stacks/$slug/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStacksSlugRoute = ApiStacksSlugRouteImport.update({
  id: '/api/stacks/$slug',
  path: '/api/stacks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIconsFromUrlRoute = ApiIconsFromUrlRouteImport.update({
  id: '/api/icons/from-url',
  path: '/api/icons/from-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliSyncRoute = ApiCliSyncRouteImport.update({
  id: '/api/cli/sync',
  path: '/api/cli/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliStacksRoute = ApiCliStacksRouteImport.update({
  id: '/api/cli/stacks',
  path: '/api/cli/stacks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliAutoSyncRoute = ApiCliAutoSyncRouteImport.update({
  id: '/api/cli/auto-sync',
  path: '/api/cli/auto-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgStackSlugRoute = ApiOgStackSlugRouteImport.update({
  id: '/api/og/stack/$slug',
  path: '/api/og/stack/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliStacksCollectRoute = ApiCliStacksCollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => ApiCliStacksRoute,
} as any)
const ApiCliAuthStartRoute = ApiCliAuthStartRouteImport.update({
  id: '/api/cli/auth/start',
  path: '/api/cli/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliAuthPollRoute = ApiCliAuthPollRouteImport.update({
  id: '/api/cli/auth/poll',
  path: '/api/cli/auth/poll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$creator': typeof CreatorRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signin-publish': typeof SigninPublishRoute
  '/sync': typeof SyncRoute
  '/test': typeof TestRoute
  '/tools': typeof ToolsRoute
  '/admin/icons': typeof AdminIconsRoute
  '/api/sync-config': typeof ApiSyncConfigRoute
  '/cli/auth': typeof CliAuthRoute
  '/prototype/freshness': typeof PrototypeFreshnessRoute
  '/prototype/views': typeof PrototypeViewsRoute
  '/prototype/views-entry': typeof PrototypeViewsEntryRoute
  '/prototype/views-stack': typeof PrototypeViewsStackRoute
  '/settings/analytics': typeof SettingsAnalyticsRoute
  '/settings/machines': typeof SettingsMachinesRoute
  '/stacks/$slug': typeof StacksSlugRoute
  '/stacks/new': typeof StacksNewRoute
  '/tools/new': typeof ToolsNewRoute
  '/waitlist/$lookupId': typeof WaitlistLookupIdRoute
  '/stacks': typeof StacksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/auto-sync': typeof ApiCliAutoSyncRoute
  '/api/cli/stacks': typeof ApiCliStacksRouteWithChildren
  '/api/cli/sync': typeof ApiCliSyncRoute
  '/api/icons/from-url': typeof ApiIconsFromUrlRoute
  '/api/stacks/$slug': typeof ApiStacksSlugRoute
  '/stacks/$slug/changes': typeof StacksSlugChangesRoute
  '/stacks/$slug/edit': typeof StacksSlugEditRoute
  '/api/cli/auth/poll': typeof ApiCliAuthPollRoute
  '/api/cli/auth/start': typeof ApiCliAuthStartRoute
  '/api/cli/stacks/collect': typeof ApiCliStacksCollectRoute
  '/api/og/stack/$slug': typeof ApiOgStackSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$creator': typeof CreatorRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signin-publish': typeof SigninPublishRoute
  '/sync': typeof SyncRoute
  '/test': typeof TestRoute
  '/tools': typeof ToolsRoute
  '/admin/icons': typeof AdminIconsRoute
  '/api/sync-config': typeof ApiSyncConfigRoute
  '/cli/auth': typeof CliAuthRoute
  '/prototype/freshness': typeof PrototypeFreshnessRoute
  '/prototype/views': typeof PrototypeViewsRoute
  '/prototype/views-entry': typeof PrototypeViewsEntryRoute
  '/prototype/views-stack': typeof PrototypeViewsStackRoute
  '/settings/analytics': typeof SettingsAnalyticsRoute
  '/settings/machines': typeof SettingsMachinesRoute
  '/stacks/$slug': typeof StacksSlugRoute
  '/stacks/new': typeof StacksNewRoute
  '/tools/new': typeof ToolsNewRoute
  '/waitlist/$lookupId': typeof WaitlistLookupIdRoute
  '/stacks': typeof StacksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/auto-sync': typeof ApiCliAutoSyncRoute
  '/api/cli/stacks': typeof ApiCliStacksRouteWithChildren
  '/api/cli/sync': typeof ApiCliSyncRoute
  '/api/icons/from-url': typeof ApiIconsFromUrlRoute
  '/api/stacks/$slug': typeof ApiStacksSlugRoute
  '/stacks/$slug/changes': typeof StacksSlugChangesRoute
  '/stacks/$slug/edit': typeof StacksSlugEditRoute
  '/api/cli/auth/poll': typeof ApiCliAuthPollRoute
  '/api/cli/auth/start': typeof ApiCliAuthStartRoute
  '/api/cli/stacks/collect': typeof ApiCliStacksCollectRoute
  '/api/og/stack/$slug': typeof ApiOgStackSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$creator': typeof CreatorRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signin-publish': typeof SigninPublishRoute
  '/sync': typeof SyncRoute
  '/test': typeof TestRoute
  '/tools': typeof ToolsRoute
  '/admin_/icons': typeof AdminIconsRoute
  '/api/sync-config': typeof ApiSyncConfigRoute
  '/cli/auth': typeof CliAuthRoute
  '/prototype/freshness': typeof PrototypeFreshnessRoute
  '/prototype/views': typeof PrototypeViewsRoute
  '/prototype/views-entry': typeof PrototypeViewsEntryRoute
  '/prototype/views-stack': typeof PrototypeViewsStackRoute
  '/settings/analytics': typeof SettingsAnalyticsRoute
  '/settings/machines': typeof SettingsMachinesRoute
  '/stacks/$slug': typeof StacksSlugRoute
  '/stacks/new': typeof StacksNewRoute
  '/tools_/new': typeof ToolsNewRoute
  '/waitlist/$lookupId': typeof WaitlistLookupIdRoute
  '/stacks/': typeof StacksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/auto-sync': typeof ApiCliAutoSyncRoute
  '/api/cli/stacks': typeof ApiCliStacksRouteWithChildren
  '/api/cli/sync': typeof ApiCliSyncRoute
  '/api/icons/from-url': typeof ApiIconsFromUrlRoute
  '/api/stacks/$slug': typeof ApiStacksSlugRoute
  '/stacks/$slug_/changes': typeof StacksSlugChangesRoute
  '/stacks/$slug_/edit': typeof StacksSlugEditRoute
  '/api/cli/auth/poll': typeof ApiCliAuthPollRoute
  '/api/cli/auth/start': typeof ApiCliAuthStartRoute
  '/api/cli/stacks/collect': typeof ApiCliStacksCollectRoute
  '/api/og/stack/$slug': typeof ApiOgStackSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$creator'
    | '/about'
    | '/activity'
    | '/admin'
    | '/auth-callback'
    | '/forgot-password'
    | '/leaderboard'
    | '/reset-password'
    | '/signin'
    | '/signin-publish'
    | '/sync'
    | '/test'
    | '/tools'
    | '/admin/icons'
    | '/api/sync-config'
    | '/cli/auth'
    | '/prototype/freshness'
    | '/prototype/views'
    | '/prototype/views-entry'
    | '/prototype/views-stack'
    | '/settings/analytics'
    | '/settings/machines'
    | '/stacks/$slug'
    | '/stacks/new'
    | '/tools/new'
    | '/waitlist/$lookupId'
    | '/stacks'
    | '/api/auth/$'
    | '/api/cli/auto-sync'
    | '/api/cli/stacks'
    | '/api/cli/sync'
    | '/api/icons/from-url'
    | '/api/stacks/$slug'
    | '/stacks/$slug/changes'
    | '/stacks/$slug/edit'
    | '/api/cli/auth/poll'
    | '/api/cli/auth/start'
    | '/api/cli/stacks/collect'
    | '/api/og/stack/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$creator'
    | '/about'
    | '/activity'
    | '/admin'
    | '/auth-callback'
    | '/forgot-password'
    | '/leaderboard'
    | '/reset-password'
    | '/signin'
    | '/signin-publish'
    | '/sync'
    | '/test'
    | '/tools'
    | '/admin/icons'
    | '/api/sync-config'
    | '/cli/auth'
    | '/prototype/freshness'
    | '/prototype/views'
    | '/prototype/views-entry'
    | '/prototype/views-stack'
    | '/settings/analytics'
    | '/settings/machines'
    | '/stacks/$slug'
    | '/stacks/new'
    | '/tools/new'
    | '/waitlist/$lookupId'
    | '/stacks'
    | '/api/auth/$'
    | '/api/cli/auto-sync'
    | '/api/cli/stacks'
    | '/api/cli/sync'
    | '/api/icons/from-url'
    | '/api/stacks/$slug'
    | '/stacks/$slug/changes'
    | '/stacks/$slug/edit'
    | '/api/cli/auth/poll'
    | '/api/cli/auth/start'
    | '/api/cli/stacks/collect'
    | '/api/og/stack/$slug'
  id:
    | '__root__'
    | '/'
    | '/$creator'
    | '/about'
    | '/activity'
    | '/admin'
    | '/auth-callback'
    | '/forgot-password'
    | '/leaderboard'
    | '/reset-password'
    | '/signin'
    | '/signin-publish'
    | '/sync'
    | '/test'
    | '/tools'
    | '/admin_/icons'
    | '/api/sync-config'
    | '/cli/auth'
    | '/prototype/freshness'
    | '/prototype/views'
    | '/prototype/views-entry'
    | '/prototype/views-stack'
    | '/settings/analytics'
    | '/settings/machines'
    | '/stacks/$slug'
    | '/stacks/new'
    | '/tools_/new'
    | '/waitlist/$lookupId'
    | '/stacks/'
    | '/api/auth/$'
    | '/api/cli/auto-sync'
    | '/api/cli/stacks'
    | '/api/cli/sync'
    | '/api/icons/from-url'
    | '/api/stacks/$slug'
    | '/stacks/$slug_/changes'
    | '/stacks/$slug_/edit'
    | '/api/cli/auth/poll'
    | '/api/cli/auth/start'
    | '/api/cli/stacks/collect'
    | '/api/og/stack/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatorRoute: typeof CreatorRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SigninPublishRoute: typeof SigninPublishRoute
  SyncRoute: typeof SyncRoute
  TestRoute: typeof TestRoute
  ToolsRoute: typeof ToolsRoute
  AdminIconsRoute: typeof AdminIconsRoute
  ApiSyncConfigRoute: typeof ApiSyncConfigRoute
  CliAuthRoute: typeof CliAuthRoute
  PrototypeFreshnessRoute: typeof PrototypeFreshnessRoute
  PrototypeViewsRoute: typeof PrototypeViewsRoute
  PrototypeViewsEntryRoute: typeof PrototypeViewsEntryRoute
  PrototypeViewsStackRoute: typeof PrototypeViewsStackRoute
  SettingsAnalyticsRoute: typeof SettingsAnalyticsRoute
  SettingsMachinesRoute: typeof SettingsMachinesRoute
  StacksSlugRoute: typeof StacksSlugRoute
  StacksNewRoute: typeof StacksNewRoute
  ToolsNewRoute: typeof ToolsNewRoute
  WaitlistLookupIdRoute: typeof WaitlistLookupIdRoute
  StacksIndexRoute: typeof StacksIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCliAutoSyncRoute: typeof ApiCliAutoSyncRoute
  ApiCliStacksRoute: typeof ApiCliStacksRouteWithChildren
  ApiCliSyncRoute: typeof ApiCliSyncRoute
  ApiIconsFromUrlRoute: typeof ApiIconsFromUrlRoute
  ApiStacksSlugRoute: typeof ApiStacksSlugRoute
  StacksSlugChangesRoute: typeof StacksSlugChangesRoute
  StacksSlugEditRoute: typeof StacksSlugEditRoute
  ApiCliAuthPollRoute: typeof ApiCliAuthPollRoute
  ApiCliAuthStartRoute: typeof ApiCliAuthStartRoute
  ApiOgStackSlugRoute: typeof ApiOgStackSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin-publish': {
      id: '/signin-publish'
      path: '/signin-publish'
      fullPath: '/signin-publish'
      preLoaderRoute: typeof SigninPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$creator': {
      id: '/$creator'
      path: '/$creator'
      fullPath: '/$creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/': {
      id: '/stacks/'
      path: '/stacks'
      fullPath: '/stacks'
      preLoaderRoute: typeof StacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/$lookupId': {
      id: '/waitlist/$lookupId'
      path: '/waitlist/$lookupId'
      fullPath: '/waitlist/$lookupId'
      preLoaderRoute: typeof WaitlistLookupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools_/new': {
      id: '/tools_/new'
      path: '/tools/new'
      fullPath: '/tools/new'
      preLoaderRoute: typeof ToolsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/new': {
      id: '/stacks/new'
      path: '/stacks/new'
      fullPath: '/stacks/new'
      preLoaderRoute: typeof StacksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$slug': {
      id: '/stacks/$slug'
      path: '/stacks/$slug'
      fullPath: '/stacks/$slug'
      preLoaderRoute: typeof StacksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/machines': {
      id: '/settings/machines'
      path: '/settings/machines'
      fullPath: '/settings/machines'
      preLoaderRoute: typeof SettingsMachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/analytics': {
      id: '/settings/analytics'
      path: '/settings/analytics'
      fullPath: '/settings/analytics'
      preLoaderRoute: typeof SettingsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/views-stack': {
      id: '/prototype/views-stack'
      path: '/prototype/views-stack'
      fullPath: '/prototype/views-stack'
      preLoaderRoute: typeof PrototypeViewsStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/views-entry': {
      id: '/prototype/views-entry'
      path: '/prototype/views-entry'
      fullPath: '/prototype/views-entry'
      preLoaderRoute: typeof PrototypeViewsEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/views': {
      id: '/prototype/views'
      path: '/prototype/views'
      fullPath: '/prototype/views'
      preLoaderRoute: typeof PrototypeViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/freshness': {
      id: '/prototype/freshness'
      path: '/prototype/freshness'
      fullPath: '/prototype/freshness'
      preLoaderRoute: typeof PrototypeFreshnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/auth': {
      id: '/cli/auth'
      path: '/cli/auth'
      fullPath: '/cli/auth'
      preLoaderRoute: typeof CliAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-config': {
      id: '/api/sync-config'
      path: '/api/sync-config'
      fullPath: '/api/sync-config'
      preLoaderRoute: typeof ApiSyncConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/icons': {
      id: '/admin_/icons'
      path: '/admin/icons'
      fullPath: '/admin/icons'
      preLoaderRoute: typeof AdminIconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$slug_/edit': {
      id: '/stacks/$slug_/edit'
      path: '/stacks/$slug/edit'
      fullPath: '/stacks/$slug/edit'
      preLoaderRoute: typeof StacksSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$slug_/changes': {
      id: '/stacks/$slug_/changes'
      path: '/stacks/$slug/changes'
      fullPath: '/stacks/$slug/changes'
      preLoaderRoute: typeof StacksSlugChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stacks/$slug': {
      id: '/api/stacks/$slug'
      path: '/api/stacks/$slug'
      fullPath: '/api/stacks/$slug'
      preLoaderRoute: typeof ApiStacksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/icons/from-url': {
      id: '/api/icons/from-url'
      path: '/api/icons/from-url'
      fullPath: '/api/icons/from-url'
      preLoaderRoute: typeof ApiIconsFromUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/sync': {
      id: '/api/cli/sync'
      path: '/api/cli/sync'
      fullPath: '/api/cli/sync'
      preLoaderRoute: typeof ApiCliSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/stacks': {
      id: '/api/cli/stacks'
      path: '/api/cli/stacks'
      fullPath: '/api/cli/stacks'
      preLoaderRoute: typeof ApiCliStacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/auto-sync': {
      id: '/api/cli/auto-sync'
      path: '/api/cli/auto-sync'
      fullPath: '/api/cli/auto-sync'
      preLoaderRoute: typeof ApiCliAutoSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/stack/$slug': {
      id: '/api/og/stack/$slug'
      path: '/api/og/stack/$slug'
      fullPath: '/api/og/stack/$slug'
      preLoaderRoute: typeof ApiOgStackSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/stacks/collect': {
      id: '/api/cli/stacks/collect'
      path: '/collect'
      fullPath: '/api/cli/stacks/collect'
      preLoaderRoute: typeof ApiCliStacksCollectRouteImport
      parentRoute: typeof ApiCliStacksRoute
    }
    '/api/cli/auth/start': {
      id: '/api/cli/auth/start'
      path: '/api/cli/auth/start'
      fullPath: '/api/cli/auth/start'
      preLoaderRoute: typeof ApiCliAuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/auth/poll': {
      id: '/api/cli/auth/poll'
      path: '/api/cli/auth/poll'
      fullPath: '/api/cli/auth/poll'
      preLoaderRoute: typeof ApiCliAuthPollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiCliStacksRouteChildren {
  ApiCliStacksCollectRoute: typeof ApiCliStacksCollectRoute
}

const ApiCliStacksRouteChildren: ApiCliStacksRouteChildren = {
  ApiCliStacksCollectRoute: ApiCliStacksCollectRoute,
}

const ApiCliStacksRouteWithChildren = ApiCliStacksRoute._addFileChildren(
  ApiCliStacksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatorRoute: CreatorRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeaderboardRoute: LeaderboardRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SigninPublishRoute: SigninPublishRoute,
  SyncRoute: SyncRoute,
  TestRoute: TestRoute,
  ToolsRoute: ToolsRoute,
  AdminIconsRoute: AdminIconsRoute,
  ApiSyncConfigRoute: ApiSyncConfigRoute,
  CliAuthRoute: CliAuthRoute,
  PrototypeFreshnessRoute: PrototypeFreshnessRoute,
  PrototypeViewsRoute: PrototypeViewsRoute,
  PrototypeViewsEntryRoute: PrototypeViewsEntryRoute,
  PrototypeViewsStackRoute: PrototypeViewsStackRoute,
  SettingsAnalyticsRoute: SettingsAnalyticsRoute,
  SettingsMachinesRoute: SettingsMachinesRoute,
  StacksSlugRoute: StacksSlugRoute,
  StacksNewRoute: StacksNewRoute,
  ToolsNewRoute: ToolsNewRoute,
  WaitlistLookupIdRoute: WaitlistLookupIdRoute,
  StacksIndexRoute: StacksIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCliAutoSyncRoute: ApiCliAutoSyncRoute,
  ApiCliStacksRoute: ApiCliStacksRouteWithChildren,
  ApiCliSyncRoute: ApiCliSyncRoute,
  ApiIconsFromUrlRoute: ApiIconsFromUrlRoute,
  ApiStacksSlugRoute: ApiStacksSlugRoute,
  StacksSlugChangesRoute: StacksSlugChangesRoute,
  StacksSlugEditRoute: StacksSlugEditRoute,
  ApiCliAuthPollRoute: ApiCliAuthPollRoute,
  ApiCliAuthStartRoute: ApiCliAuthStartRoute,
  ApiOgStackSlugRoute: ApiOgStackSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
