/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TestRouteImport } from './routes/test'
import { Route as SigninPublishRouteImport } from './routes/signin-publish'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StacksIndexRouteImport } from './routes/stacks.index'
import { Route as WaitlistLookupIdRouteImport } from './routes/waitlist.$lookupId'
import { Route as StacksNewRouteImport } from './routes/stacks.new'
import { Route as StacksSlugRouteImport } from './routes/stacks.$slug'
import { Route as AdminToolsRouteImport } from './routes/admin.tools'
import { Route as StacksSlugEditRouteImport } from './routes/stacks.$slug_.edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninPublishRoute = SigninPublishRouteImport.update({
  id: '/signin-publish',
  path: '/signin-publish',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksIndexRoute = StacksIndexRouteImport.update({
  id: '/stacks/',
  path: '/stacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistLookupIdRoute = WaitlistLookupIdRouteImport.update({
  id: '/waitlist/$lookupId',
  path: '/waitlist/$lookupId',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksNewRoute = StacksNewRouteImport.update({
  id: '/stacks/new',
  path: '/stacks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksSlugRoute = StacksSlugRouteImport.update({
  id: '/stacks/$slug',
  path: '/stacks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/admin/tools',
  path: '/admin/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksSlugEditRoute = StacksSlugEditRouteImport.update({
  id: '/stacks/$slug_/edit',
  path: '/stacks/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signin-publish': typeof SigninPublishRoute
  '/test': typeof TestRoute
  '/tools': typeof ToolsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/stacks/$slug': typeof StacksSlugRoute
  '/stacks/new': typeof StacksNewRoute
  '/waitlist/$lookupId': typeof WaitlistLookupIdRoute
  '/stacks': typeof StacksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/stacks/$slug/edit': typeof StacksSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signin-publish': typeof SigninPublishRoute
  '/test': typeof TestRoute
  '/tools': typeof ToolsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/stacks/$slug': typeof StacksSlugRoute
  '/stacks/new': typeof StacksNewRoute
  '/waitlist/$lookupId': typeof WaitlistLookupIdRoute
  '/stacks': typeof StacksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/stacks/$slug/edit': typeof StacksSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signin-publish': typeof SigninPublishRoute
  '/test': typeof TestRoute
  '/tools': typeof ToolsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/stacks/$slug': typeof StacksSlugRoute
  '/stacks/new': typeof StacksNewRoute
  '/waitlist/$lookupId': typeof WaitlistLookupIdRoute
  '/stacks/': typeof StacksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/stacks/$slug_/edit': typeof StacksSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth-callback'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signin-publish'
    | '/test'
    | '/tools'
    | '/admin/tools'
    | '/stacks/$slug'
    | '/stacks/new'
    | '/waitlist/$lookupId'
    | '/stacks'
    | '/api/auth/$'
    | '/stacks/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth-callback'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signin-publish'
    | '/test'
    | '/tools'
    | '/admin/tools'
    | '/stacks/$slug'
    | '/stacks/new'
    | '/waitlist/$lookupId'
    | '/stacks'
    | '/api/auth/$'
    | '/stacks/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth-callback'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signin-publish'
    | '/test'
    | '/tools'
    | '/admin/tools'
    | '/stacks/$slug'
    | '/stacks/new'
    | '/waitlist/$lookupId'
    | '/stacks/'
    | '/api/auth/$'
    | '/stacks/$slug_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SigninPublishRoute: typeof SigninPublishRoute
  TestRoute: typeof TestRoute
  ToolsRoute: typeof ToolsRoute
  AdminToolsRoute: typeof AdminToolsRoute
  StacksSlugRoute: typeof StacksSlugRoute
  StacksNewRoute: typeof StacksNewRoute
  WaitlistLookupIdRoute: typeof WaitlistLookupIdRoute
  StacksIndexRoute: typeof StacksIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  StacksSlugEditRoute: typeof StacksSlugEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin-publish': {
      id: '/signin-publish'
      path: '/signin-publish'
      fullPath: '/signin-publish'
      preLoaderRoute: typeof SigninPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/': {
      id: '/stacks/'
      path: '/stacks'
      fullPath: '/stacks'
      preLoaderRoute: typeof StacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/$lookupId': {
      id: '/waitlist/$lookupId'
      path: '/waitlist/$lookupId'
      fullPath: '/waitlist/$lookupId'
      preLoaderRoute: typeof WaitlistLookupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/new': {
      id: '/stacks/new'
      path: '/stacks/new'
      fullPath: '/stacks/new'
      preLoaderRoute: typeof StacksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$slug': {
      id: '/stacks/$slug'
      path: '/stacks/$slug'
      fullPath: '/stacks/$slug'
      preLoaderRoute: typeof StacksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/admin/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$slug_/edit': {
      id: '/stacks/$slug_/edit'
      path: '/stacks/$slug/edit'
      fullPath: '/stacks/$slug/edit'
      preLoaderRoute: typeof StacksSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SigninPublishRoute: SigninPublishRoute,
  TestRoute: TestRoute,
  ToolsRoute: ToolsRoute,
  AdminToolsRoute: AdminToolsRoute,
  StacksSlugRoute: StacksSlugRoute,
  StacksNewRoute: StacksNewRoute,
  WaitlistLookupIdRoute: WaitlistLookupIdRoute,
  StacksIndexRoute: StacksIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  StacksSlugEditRoute: StacksSlugEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
